export const ROUTE_NAME                 = 'cart'

export const CART_CREATE_REQUEST        = 'CART_CREATE_REQUEST'
export const CART_CREATE_SUCCESS        = 'CART_CREATE_SUCCESS'
export const CART_CREATE_FAIL           = 'CART_CREATE_FAIL'

export const CART_UPDATE_REQUEST        = 'CART_UPDATE_REQUEST'
export const CART_UPDATE_SUCCESS        = 'CART_UPDATE_SUCCESS'
export const CART_UPDATE_FAIL           = 'CART_UPDATE_FAIL'

export const CART_CHANGE_STATUS_REQUEST = 'CART_CHANGE_STATUS_REQUEST'
export const CART_CHANGE_STATUS_SUCCESS = 'CART_CHANGE_STATUS_SUCCESS'
export const CART_CHANGE_STATUS_FAIL    = 'CART_CHANGE_STATUS_FAIL'

export const CART_GET_ALL_REQUEST       = 'CART_GET_ALL_REQUEST'
export const CART_GET_ALL_SUCCESS       = 'CART_GET_ALL_SUCCESS'
export const CART_GET_ALL_FAIL          = 'CART_GET_ALL_FAIL'

export const CART_GET_BY_UUID_REQUEST   = 'CART_GET_BY_UUID_REQUEST'
export const CART_GET_BY_UUID_SUCCESS   = 'CART_GET_BY_UUID_SUCCESS'
export const CART_GET_BY_UUID_FAIL      = 'CART_GET_BY_UUID_FAIL'

export const CART_GET_ALL_ITEM_REQUEST  = 'CART_GET_ALL_ITEM_REQUEST'
export const CART_GET_ALL_ITEM_SUCCESS  = 'CART_GET_ALL_ITEM_SUCCESS'
export const CART_GET_ALL_ITEM_FAIL     = 'CART_GET_ALL_ITEM_FAIL'
