

export const ROUTE_NAME                     = 'products'

export const PRODUCTS_CREATE_REQUEST        = 'PRODUCTS_CREATE_REQUEST'
export const PRODUCTS_CREATE_SUCCESS        = 'PRODUCTS_CREATE_SUCCESS'
export const PRODUCTS_CREATE_FAIL           = 'PRODUCTS_CREATE_FAIL'

export const PRODUCTS_UPDATE_REQUEST        = 'PRODUCTS_UPDATE_REQUEST'
export const PRODUCTS_UPDATE_SUCCESS        = 'PRODUCTS_UPDATE_SUCCESS'
export const PRODUCTS_UPDATE_FAIL           = 'PRODUCTS_UPDATE_FAIL'

export const PRODUCTS_CHANGE_STATUS_REQUEST = 'PRODUCTS_CHANGE_STATUS_REQUEST'
export const PRODUCTS_CHANGE_STATUS_SUCCESS = 'PRODUCTS_CHANGE_STATUS_SUCCESS'
export const PRODUCTS_CHANGE_STATUS_FAIL    = 'PRODUCTS_CHANGE_STATUS_FAIL'

export const PRODUCTS_GET_ALL_REQUEST       = 'PRODUCTS_GET_ALL_REQUEST'
export const PRODUCTS_GET_ALL_SUCCESS       = 'PRODUCTS_GET_ALL_SUCCESS'
export const PRODUCTS_GET_ALL_FAIL          = 'PRODUCTS_GET_ALL_FAIL'

export const PRODUCTS_GET_BY_UUID_REQUEST   = 'PRODUCTS_GET_BY_UUID_REQUEST'
export const PRODUCTS_GET_BY_UUID_SUCCESS   = 'PRODUCTS_GET_BY_UUID_SUCCESS'
export const PRODUCTS_GET_BY_UUID_FAIL      = 'PRODUCTS_GET_BY_UUID_FAIL'

export const PRODUCTS_GET_ALL_ITEM_REQUEST  = 'PRODUCTS_GET_ALL_ITEM_REQUEST'
export const PRODUCTS_GET_ALL_ITEM_SUCCESS  = 'PRODUCTS_GET_ALL_ITEM_SUCCESS'
export const PRODUCTS_GET_ALL_ITEM_FAIL     = 'PRODUCTS_GET_ALL_ITEM_FAIL'
